import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import React from "react";
import Navbar from "~/app/_components/navbar";
import { Providers } from "~/app/_components/providers";
import { SessionProvider } from "~/app/context/SessionContext";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Providers>
          <SessionProvider>
            <Navbar />
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
